spring:
  activemq:
    in-memory: true
    non-blocking-redelivery: false
    broker-url: vm://localhost?broker.schedulerSupport=true&broker.deleteAllMessagesOnStartup=true
  jpa:
    show-sql: true
  jms:
    listener:
      acknowledge-mode: client
    template:
      default-destination:
      delivery-mode: persistent

logging:
  level:
    count: DEBUG
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jgame:
  jms:
    constructions:
      destination: Constructions
      retryFailed: false
      failedDestination: Constructions_FAILED
      minDelay: 100
      retryDelay: 1000
      failedDelay: 2000
    shipyard:
      destination: Shipyyyyard
      retryFailed: false
      failedDestination: Shipyard_FAILED
      minDelay: 100
      retryDelay: 1000
      failedDelay: 2000
  game:
    defaultAdministrableLocation:
      name: "First planet"
      typeId: 1